-- MeshSwap: replaces the part-built reef rocks in CoralReef with the deformed,
-- stud-textured Blender meshes. (The island keeps its blocky voxel rocks on purpose.)
--
-- 1. File > Import 3D > exports/meshes/VoxelRockMeshes.fbx  (it lands in Workspace)
-- 2. Paste this whole file into the Command Bar (View > Command Bar) and press Enter.
--
-- Every mesh piece is placed from its exact size/centre (baked in below by Blender),
-- so it doesn't matter how the importer scaled or grouped the meshes.
-- Running it again is safe. Set UNDO = true and run it to put the part rocks back.

local UNDO = false

-- generated by tools/blender_meshes.py: asset -> mesh pieces (asset space, studs)
local PIECES = {
	ReefPinnacle = {
		{ suffix = "_Rock", min = Vector3.new(-7.703, -0.661, -6.388), max = Vector3.new(7.911, 22.495, 6.494), color = Color3.fromRGB(112, 138, 230) },
		{ suffix = "_Top", min = Vector3.new(-7.456, 2.246, -5.905), max = Vector3.new(7.818, 23.002, 6.374), color = Color3.fromRGB(246, 226, 112) },
	},
	ReefPinnacleTall = {
		{ suffix = "_Rock", min = Vector3.new(-9.133, -0.841, -8.052), max = Vector3.new(10.593, 26.323, 7.567), color = Color3.fromRGB(112, 138, 230) },
		{ suffix = "_Top", min = Vector3.new(-9.133, 0.269, -7.672), max = Vector3.new(10.417, 26.323, 7.567), color = Color3.fromRGB(246, 226, 112) },
	},
	ReefShelf = {
		{ suffix = "_Rock", min = Vector3.new(-14.621, -0.602, -8.482), max = Vector3.new(14.384, 14.558, 8.563), color = Color3.fromRGB(112, 138, 230) },
		{ suffix = "_Top", min = Vector3.new(-14.555, 10.378, -8.045), max = Vector3.new(14.384, 14.702, 8.563), color = Color3.fromRGB(246, 226, 112) },
	},
	ReefArch = {
		{ suffix = "_Rock", min = Vector3.new(-11.496, -0.338, -4.766), max = Vector3.new(11.534, 15.261, 4.638), color = Color3.fromRGB(112, 138, 230) },
		{ suffix = "_Top", min = Vector3.new(-10.906, 0.219, -4.728), max = Vector3.new(10.466, 15.469, 4.511), color = Color3.fromRGB(246, 226, 112) },
	},
	Boulder = {
		{ suffix = "_Rock", min = Vector3.new(-4.867, -0.417, -4.939), max = Vector3.new(5.059, 6.873, 4.983), color = Color3.fromRGB(168, 178, 222) },
	},
	Seaweed = {
		{ suffix = "_Rock", min = Vector3.new(-3.223, -0.041, -3.636), max = Vector3.new(3.679, 13.116, 2.195), color = Color3.fromRGB(60, 176, 66) },
	},
}
local PRECISE = { ReefShelf = true, ReefArch = true, ReefPinnacle = true, ReefPinnacleTall = true }
local MAPS = { "VoxelIsland", "CoralReef" }

local ServerStorage = game:GetService("ServerStorage")
local function waypoint(name)
	pcall(function()
		game:GetService("ChangeHistoryService"):SetWaypoint(name)
	end)
end

local backup = ServerStorage:FindFirstChild("VoxelPartRocks")
if not backup then
	backup = Instance.new("Folder")
	backup.Name = "VoxelPartRocks"
	backup.Parent = ServerStorage
end

-- remove meshes from an earlier run and put the part rocks back ---------------------
local function restore()
	local n = 0
	for _, mapName in ipairs(MAPS) do
		local map = workspace:FindFirstChild(mapName)
		if map then
			local old = {}
			for _, d in ipairs(map:GetDescendants()) do
				if d:IsA("Model") and d:GetAttribute("VoxelMesh") then
					table.insert(old, d)
				end
			end
			for _, d in ipairs(old) do
				d:Destroy()
			end
		end
	end
	for _, m in ipairs(backup:GetChildren()) do
		local home = m:FindFirstChild("VoxelOriginalParent")
		if home and home.Value and home.Value.Parent then
			m.Parent = home.Value
			home:Destroy()
			n += 1
		end
	end
	return n
end

waypoint("Before MeshSwap")
local restored = restore()
if UNDO then
	waypoint("MeshSwap undo")
	print(("[MeshSwap] restored %d part rocks"):format(restored))
	return
end

-- 1. find the imported mesh pieces (names like ReefShelf_Rock, maybe with .001 on the end)
local function norm(name)
	return (name:gsub("%.%d+$", ""))
end
local found = {}
for _, root in ipairs({ workspace, game:GetService("ReplicatedStorage"), ServerStorage }) do
	for _, top in ipairs(root:GetChildren()) do
		if top.Name ~= "VoxelIsland" and top.Name ~= "CoralReef" and top ~= backup then
			local list = top:GetDescendants()
			table.insert(list, top)
			for _, d in ipairs(list) do
				if d:IsA("MeshPart") then
					local key = norm(d.Name)
					if PIECES[key:match("^(.-)_[^_]+$") or ""] and not found[key] then
						found[key] = d
					end
				end
			end
		end
	end
end

local ready, missing = {}, {}
local votes = { straight = 0, lying = 0 }
for name, pieces in pairs(PIECES) do
	local ok = true
	for _, piece in ipairs(pieces) do
		local tmpl = found[name .. piece.suffix]
		if not tmpl then
			ok = false
		else
			-- the imported mesh should have our proportions; if it matches with Y and Z swapped,
			-- the importer laid it on its side. The importer treats every mesh the same way,
			-- so collect votes and decide once for all of them.
			local want = piece.max - piece.min
			local function spread(a, b)
				local r = { a.X / b.X, a.Y / b.Y, a.Z / b.Z }
				table.sort(r)
				return r[3] / r[1]
			end
			local straight = spread(tmpl.Size, want)
			local sideways = spread(tmpl.Size, Vector3.new(want.X, want.Z, want.Y))
			if straight < 1.1 and sideways > 1.2 then
				votes.straight += 1
			elseif sideways < 1.1 and straight > 1.2 then
				votes.lying += 1
			end
		end
	end
	if ok then
		ready[name] = pieces
	else
		table.insert(missing, name)
	end
end
local LYING = votes.lying > votes.straight
if LYING then
	warn("[MeshSwap] the importer laid the meshes on their sides - standing them back up")
end
if next(ready) == nil then
	warn("[MeshSwap] No imported rock meshes found. Import exports/meshes/VoxelRockMeshes.fbx first.")
	return
end
if #missing > 0 then
	table.sort(missing)
	warn("[MeshSwap] not found in the import (left as parts): " .. table.concat(missing, ", "))
end

-- 2. swap every tagged rock ----------------------------------------------------------
local swapped = 0
for _, mapName in ipairs(MAPS) do
	local map = workspace:FindFirstChild(mapName)
	if map then
		for _, m in ipairs(map:GetDescendants()) do
			local name = m:IsA("Model") and not m:GetAttribute("VoxelMesh") and m:GetAttribute("VoxelAsset")
			local pieces = name and ready[name]
			if pieces then
				local scale = m:GetAttribute("VoxelScale") or 1
				local ref, offset = m:FindFirstChild("VoxelRef"), m:GetAttribute("VoxelRefOffset")
				local cf = (ref and offset) and ref.CFrame * offset or m.WorldPivot
				local model = Instance.new("Model")
				model.Name = name
				for _, piece in ipairs(pieces) do
					local p = found[name .. piece.suffix]:Clone()
					p.Name = name .. piece.suffix
					local size = (piece.max - piece.min) * scale
					local at = cf * CFrame.new((piece.min + piece.max) * 0.5 * scale)
					if LYING then -- mesh's up is its local +Z
						p.Size = Vector3.new(size.X, size.Z, size.Y)
						p.CFrame = at * CFrame.Angles(math.rad(-90), 0, 0)
					else
						p.Size = size
						p.CFrame = at
					end
					p.Color = piece.color
					p.Anchored = true
					p.CanCollide = name ~= "Seaweed"
					p.CanTouch = false
					if PRECISE[name] then
						pcall(function()
							p.CollisionFidelity = Enum.CollisionFidelity.PreciseConvexDecomposition
						end)
					end
					p.Parent = model
				end
				model.WorldPivot = cf
				model:SetAttribute("VoxelPivot", cf)
				model:SetAttribute("VoxelAsset", name)
				model:SetAttribute("VoxelMesh", true)
				for _, d in ipairs(m:GetChildren()) do
					if d.Name == "LightSource" or d.Name == "FireSource" then
						d.Parent = model
					end
				end
				model.Parent = m.Parent
				local home = Instance.new("ObjectValue")
				home.Name = "VoxelOriginalParent"
				home.Value = m.Parent
				home.Parent = m
				m.Parent = backup
				swapped += 1
			end
		end
	end
end
waypoint("MeshSwap")
print(("[MeshSwap] swapped %d rocks for meshes (part versions kept in ServerStorage.VoxelPartRocks)."):format(swapped))
print("[MeshSwap] You can delete the imported VoxelRockMeshes model now.")
