"""Write the Roblox Studio Command Bar script that turns the imported FBX meshes
into the rigged Grim Reaper boss (Humanoid, Motor6Ds, effects, controller).

    python tools/gen_boss.py <rig.json> <controller.lua> <out.lua> [--controller-out=ReaperController.lua]

The controller gets the Throw's flight path and aim table baked in from the animation.
"""
import json
import math
import sys


def num(v, nd=4):
    s = ("%." + str(nd) + "f") % v
    s = s.rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def v3(v):
    return "Vector3.new(%s)" % ", ".join(num(x) for x in v)


HEADER = '''--[[
FOLK VALLEY [RUN] - Grim Reaper boss builder (generated by tools/gen_boss.py)

1. In Studio: File > Import 3D > choose FolkValley_GrimReaper.fbx > Import.
   Default import settings are fine ("Merge Meshes" must stay off).
   The meshes come in plain grey: that's normal, step 2 colours them.
2. View > Command Bar: paste ALL of this file and press Enter.

It builds the Model "GrimReaper" in Workspace, standing on the ground where
your camera is looking (move it wherever you like):
  * HumanoidRootPart + Humanoid (R15-style, HipHeight %s) + Animator
  * %d MeshParts on %d bones, joined by Motor6Ds with the R15 names
    (Root, Waist, Neck, LeftShoulder ... RightAnkle) plus Jaw, ScytheGrip,
    RobeFront/Back/Left/Right and Cape
  * glowing eyes (PointLight), ghostly mist round the hem, a trail on the
    scythe blade (switched on during attacks) and attachments the game can use:
    Overhead, EyeGlow, Mouth, LeftStomp, RightStomp, BladeTip, BladeBase
  * the ReaperController script (animations + a simple chase-and-attack AI,
    see the attributes on the model)
The imported model is cleaned up afterwards. Ctrl+Z undoes the whole thing.
]]

local MARKER_STEP = 4
local MODEL_NAME = "GrimReaper"
'''

BODY = r'''
local ChangeHistoryService = game:GetService("ChangeHistoryService")
local ServerStorage = game:GetService("ServerStorage")
local TAG = "FolkValley Grim Reaper: "

-- 1. find the imported meshes (the importer puts them in Workspace)
local meshes, loose = {}, {}
local function norm(s)
	return (string.lower(s):gsub("[^%w]", ""))
end
for _, root in ipairs({workspace, ServerStorage, game:GetService("ReplicatedStorage")}) do
	for _, d in ipairs(root:GetDescendants()) do
		if d:IsA("MeshPart") then
			if meshes[d.Name] == nil then
				meshes[d.Name] = d
			end
			if loose[norm(d.Name)] == nil then
				loose[norm(d.Name)] = d
			end
		end
	end
end
local function mesh(name)
	return meshes[name] or loose[norm(name)]
end
local missing = {}
for _, name in ipairs({"FV_AxisO", "FV_AxisX", "FV_AxisY", "FV_AxisZ"}) do
	if mesh(name) == nil then
		table.insert(missing, name)
	end
end
for _, p in ipairs(PARTS) do
	if mesh(p.Mesh) == nil then
		table.insert(missing, p.Mesh)
	end
end
if #missing > 0 then
	warn(TAG .. #missing .. " imported meshes not found (first: " .. missing[1]
		.. "). Import FolkValley_GrimReaper.fbx with File > Import 3D first, with Merge Meshes off.")
	return
end

-- 2. work out how the importer scaled / turned the file from the marker cubes
local o = mesh("FV_AxisO").Position
local ex = mesh("FV_AxisX").Position - o
local ey = mesh("FV_AxisY").Position - o
local ez = mesh("FV_AxisZ").Position - o
local scale = (ex.Magnitude + ey.Magnitude + ez.Magnitude) / (3 * MARKER_STEP)
if ex.Unit:Cross(ey.Unit):Dot(ez.Unit) < 0.9 then
	warn(TAG .. "the import looks mirrored. Re-import with the default axis settings.")
	return
end
local fromFile = CFrame.fromMatrix(Vector3.zero, ex.Unit, ey.Unit, ez.Unit):Inverse()

ChangeHistoryService:SetWaypoint("Before building the Grim Reaper")

-- 3. the model, built standing at BUILD_AT (model space = Roblox space, facing -Z)
local BUILD_AT = CFrame.new(0, 2000, 0)
local model = Instance.new("Model")
model.Name = MODEL_NAME
local function flags(part, collide)
	part.Anchored = false
	part.CanCollide = collide
	part.CanTouch = true
	part.CanQuery = true
	part.Massless = not collide
end
local hrp = Instance.new("Part")
hrp.Name = "HumanoidRootPart"
hrp.Size = HRP.Size
hrp.CFrame = BUILD_AT * CFrame.new(HRP.Center)
hrp.Transparency = 1
hrp.TopSurface = Enum.SurfaceType.Smooth
hrp.BottomSurface = Enum.SurfaceType.Smooth
flags(hrp, true)
hrp.Parent = model
local bones = {HumanoidRootPart = hrp}
local containers = {}
for _, p in ipairs(PARTS) do
	local part = mesh(p.Mesh)
	containers[part.Parent] = true
	local turn = fromFile * (part.CFrame - part.CFrame.Position)
	for _, child in ipairs(part:GetChildren()) do
		child:Destroy() -- importer extras (SurfaceAppearance, attachments)
	end
	part.Name = p.Name
	part.Size = part.Size / scale
	part.CFrame = BUILD_AT * CFrame.new(p.Center) * turn
	part.Color = p.Color
	part.Material = p.Material
	part.Transparency = p.Transparency
	part.Reflectance = 0
	part.CastShadow = true
	pcall(function() part.TextureID = "" end)
	pcall(function() part.CollisionFidelity = Enum.CollisionFidelity.Box end)
	flags(part, false)
	part.Parent = model
	if p.Name == p.Bone then
		bones[p.Bone] = part
	end
end
for _, p in ipairs(PARTS) do -- the rest of each bone is welded to its main part
	if p.Name ~= p.Bone then
		local part = model:FindFirstChild(p.Name)
		local weld = Instance.new("WeldConstraint")
		weld.Part0 = bones[p.Bone]
		weld.Part1 = part
		weld.Parent = part
	end
end
for _, j in ipairs(RIG) do
	local p0, p1 = bones[j.Part0], bones[j.Part1]
	local pivot = BUILD_AT * CFrame.new(j.Pivot)
	local motor = Instance.new("Motor6D")
	motor.Name = j.Motor
	motor.Part0 = p0
	motor.Part1 = p1
	motor.C0 = p0.CFrame:Inverse() * pivot
	motor.C1 = p1.CFrame:Inverse() * pivot
	motor.Parent = p1
end

local humanoid = Instance.new("Humanoid")
humanoid.RigType = Enum.HumanoidRigType.R15
humanoid.AutomaticScalingEnabled = false
humanoid.HipHeight = HIP_HEIGHT
humanoid.BreakJointsOnDeath = false
humanoid.RequiresNeck = false
humanoid.MaxHealth = DEFAULT_ATTRIBUTES.MaxHealth
humanoid.Health = DEFAULT_ATTRIBUTES.MaxHealth
humanoid.WalkSpeed = DEFAULT_ATTRIBUTES.WalkSpeed
pcall(function() humanoid.UseJumpPower = true end)
humanoid.JumpPower = 0
humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
humanoid.HealthDisplayType = Enum.HumanoidHealthDisplayType.AlwaysOff
humanoid.Parent = model
Instance.new("Animator").Parent = humanoid

local attach = {}
for _, a in ipairs(ATTACH) do
	local at = Instance.new("Attachment")
	at.Name = a.Name
	at.CFrame = bones[a.Bone].CFrame:Inverse() * (BUILD_AT * CFrame.new(a.Position))
	at.Parent = bones[a.Bone]
	attach[a.Name] = at
end

-- effects: all built-in, nothing to upload
pcall(function()
	local light = Instance.new("PointLight")
	light.Color = GLOW
	light.Brightness = 3
	light.Range = 16
	light.Shadows = false
	light.Parent = attach.EyeGlow
end)
pcall(function()
	local area = Instance.new("Part")
	area.Name = "MistArea"
	area.Size = Vector3.new(9, 0.4, 7.5)
	area.CFrame = BUILD_AT * CFrame.new(0, 0.5, 0)
	area.Transparency = 1
	area.Anchored = false
	area.CanCollide = false
	area.CanTouch = false
	area.CanQuery = false
	area.Massless = true
	area.Parent = model
	local weld = Instance.new("WeldConstraint")
	weld.Part0 = bones.LowerTorso
	weld.Part1 = area
	weld.Parent = area
	local mist = Instance.new("ParticleEmitter")
	mist.Name = "Mist"
	mist.Texture = "rbxasset://textures/particles/smoke_main.dds"
	mist.Color = ColorSequence.new(MIST, Color3.fromRGB(20, 12, 34))
	mist.Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 2.5), NumberSequenceKeypoint.new(1, 6)})
	mist.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.25, 0.55),
		NumberSequenceKeypoint.new(1, 1)})
	mist.Lifetime = NumberRange.new(2, 3.2)
	mist.Rate = 12
	mist.Speed = NumberRange.new(0.4, 1.4)
	mist.SpreadAngle = Vector2.new(180, 180)
	mist.Acceleration = Vector3.new(0, 0.5, 0)
	mist.RotSpeed = NumberRange.new(-25, 25)
	mist.Rotation = NumberRange.new(0, 360)
	mist.LightEmission = 0.15
	mist.Shape = Enum.ParticleEmitterShape.Box
	mist.ShapeStyle = Enum.ParticleEmitterShapeStyle.Volume
	mist.Parent = area
end)
pcall(function()
	local trail = Instance.new("Trail")
	trail.Name = "ScytheTrail"
	trail.Attachment0 = attach.BladeBase
	trail.Attachment1 = attach.BladeTip
	trail.Color = ColorSequence.new(GLOW, Color3.fromRGB(150, 70, 230))
	trail.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.15), NumberSequenceKeypoint.new(1, 1)})
	trail.Lifetime = 0.35
	trail.LightEmission = 1
	trail.FaceCamera = false
	trail.Enabled = false
	trail.Parent = bones.Scythe
end)

local controller = Instance.new("Script")
controller.Name = "ReaperController"
local okSource = pcall(function() controller.Source = CONTROLLER_SOURCE end)
controller.Parent = model
if not okSource then
	warn(TAG .. "couldn't write the controller script; paste ReaperController.lua into it by hand")
end
for k, v in pairs(DEFAULT_ATTRIBUTES) do
	model:SetAttribute(k, v)
end
model.PrimaryPart = hrp

-- 4. stand it on the ground where the camera is looking, facing the camera
local spot = CFrame.new(0, 0, 0)
pcall(function()
	local cam = workspace.CurrentCamera
	local focus = cam.Focus.Position
	local params = RaycastParams.new()
	params.FilterDescendantsInstances = {model}
	local hit = workspace:Raycast(focus + Vector3.new(0, 60, 0), Vector3.new(0, -400, 0), params)
	local ground = hit and hit.Position or focus
	local look = (cam.CFrame.Position - ground) * Vector3.new(1, 0, 1)
	if look.Magnitude < 1e-3 then
		look = Vector3.new(0, 0, 1)
	end
	-- the model faces -Z: point that at the camera
	spot = CFrame.lookAt(ground, ground + look.Unit)
end)
model.Parent = workspace
model:PivotTo(spot * CFrame.new(HRP.Center))

-- 5. tidy up: every marker cube (from every import of the file) and the now-empty imported model
for _, root in ipairs({workspace, ServerStorage, game:GetService("ReplicatedStorage")}) do
	for _, d in ipairs(root:GetDescendants()) do
		if d:IsA("BasePart") and d.Name:match("^FV_Axis[OXYZ]$") then
			containers[d.Parent] = true
			d:Destroy()
		end
	end
end
for container in pairs(containers) do
	local c = container
	while c and c ~= game and c ~= workspace and c.Parent and not c:IsA("Folder") do
		local hasParts = false
		for _, d in ipairs(c:GetDescendants()) do
			if d:IsA("BasePart") then
				hasParts = true
				break
			end
		end
		if hasParts then
			break
		end
		local parent = c.Parent
		c:Destroy()
		c = parent
	end
end

ChangeHistoryService:SetWaypoint("Built the Grim Reaper")
game:GetService("Selection"):Set({model})
print(TAG .. "built Workspace." .. model.Name .. " (" .. #PARTS .. " mesh parts). Drag GrimReaper_Animations.rbxm into "
	.. "ServerStorage for its animations; see the README for publishing them.")
'''


# attributes the controller reads (tweak them on the model in Studio)
ATTRS = {
    "AI": True,                 # chase and attack players on its own
    "AggroRange": 140,          # how far away it notices players
    "WalkSpeed": 8,             # studs per second while stalking (the walk is made for about 7)
    "ChaseSpeed": 20,           # studs per second while running at a target (the run is made for about 18)
    "AttackCooldown": 2.5,      # seconds between attacks
    "MaxHealth": 1000,          # the boss's health
    "Damage": 0,                # health taken per hit (0 = only knockback + the ReaperHit event)
    "Knockback": 70,            # how hard a hit throws players
    "HealthBar": True,          # the boss bar over its head
    "RemoveOnDefeat": True,     # fade away and remove itself after the defeat animation
}
ANIMS = ["Idle", "Walk", "Run", "Stomp", "Swing", "Spin", "Throw", "Roar", "Hurt", "Defeat"]
for _a in ANIMS:
    ATTRS["Anim" + _a] = ""     # published animation ids go here


def throw_data(rig_path):
    """The whirling scythe's path during the Throw (Release to Catch), from the baked
    animation: [(seconds after Release, offset from the root part)], and the aim table
    [(target distance, degrees to turn left)] that puts a target on its way out."""
    import numpy as np
    import reaper_anims as RA
    rig, ctx, clips = RA.build_all(rig_path)
    clip, times, frames = next(c for c in clips if c[0].name == "ReaperThrow")
    marks = dict((n, t) for t, n in clip.markers)
    t0, t1 = marks["Release"], marks["Catch"]
    hrp = rig.rest["HumanoidRootPart"][:3, 3]
    mid = np.array([*ctx.scythe_mid, 1.0])
    path = []
    for t, X in zip(times, frames):
        if t0 - 1e-6 <= t <= t1 + 1e-6:
            W = rig.fk(X)
            p = (W["Scythe"] @ np.linalg.inv(rig.rest["Scythe"]) @ mid)[:3] - hrp
            path.append((round(t - t0, 4), *[round(float(v), 3) for v in p]))
    far = max(range(len(path)), key=lambda i: math.hypot(path[i][1], path[i][3]))
    out = [(math.hypot(p[1], p[3]), math.degrees(math.atan2(p[1], -p[3]))) for p in path[:far + 1]]
    aim = []
    for r in range(12, 36, 2):
        d, b = min(out, key=lambda q: abs(q[0] - r))
        if abs(d - r) < 2.5:
            aim.append((r, round(b, 1)))
    return path, aim


def lua_rows(rows):
    return "{" + ", ".join("{" + ", ".join(num(v, 3) for v in r) + "}" for r in rows) + "}"


def fill_controller(src, rig_path):
    path, aim = throw_data(rig_path)
    a = "local THROW_PATH = {} -- filled in by gen_boss.py"
    b = "local THROW_AIM = {} -- filled in by gen_boss.py"
    assert a in src and b in src
    src = src.replace(a, "local THROW_PATH = " + lua_rows(path))
    src = src.replace(b, "local THROW_AIM = " + lua_rows(aim))
    return src


def main(rig_path, controller_path, out, controller_out=None):
    rig = json.load(open(rig_path))
    parts = rig["Parts"]
    hip = rig["HRP"]["Center"][1] - rig["HRP"]["Size"][1] / 2
    bones = sorted({p["Model"] for p in parts})
    lines = [HEADER % (num(hip, 2), len(parts), len(bones))]
    lines.append("local HRP = {Center = %s, Size = %s}" % (v3(rig["HRP"]["Center"]), v3(rig["HRP"]["Size"])))
    lines.append("local HIP_HEIGHT = %s" % num(hip, 3))
    lines.append("local GLOW = Color3.fromRGB(122, 255, 106)")
    lines.append("local MIST = Color3.fromRGB(96, 64, 140)")
    lines.append("local PARTS = {")
    for p in parts:
        lines.append('\t{Name = "%s", Mesh = "%s", Bone = "%s", Color = Color3.fromRGB(%d, %d, %d), Material = '
                     'Enum.Material.%s, Transparency = %s, Center = %s},' % (
                         p["Name"], p["Mesh"], p["Model"], *p["Color"], p["Material"], num(p["Transparency"]),
                         v3(p["Center"])))
    lines.append("}")
    lines.append("local RIG = {")
    for j in rig["Rig"]:
        lines.append('\t{Motor = "%s", Part0 = "%s", Part1 = "%s", Pivot = %s},' % (j["Motor"], j["Part0"], j["Part1"],
                                                                                 v3(j["Pivot"])))
    lines.append("}")
    lines.append("local ATTACH = {")
    for a in rig["Attachments"]:
        lines.append('\t{Name = "%s", Bone = "%s", Position = %s},' % (a["Name"], a["Bone"], v3(a["Position"])))
    lines.append("}")
    lines.append("local DEFAULT_ATTRIBUTES = {")
    for k, v in ATTRS.items():
        lines.append('\t%s = %s,' % (k, ("%s" % ("true" if v else "false")) if isinstance(v, bool) else
                                     (num(v) if isinstance(v, (int, float)) else '"%s"' % v)))
    lines.append("}")
    src = fill_controller(open(controller_path).read(), rig_path)
    if controller_out:
        with open(controller_out, "w") as f:
            f.write(src)
    level = 1
    while ("]" + "=" * level + "]") in src:
        level += 1
    lines.append("local CONTROLLER_SOURCE = [" + "=" * level + "[\n" + src + "]" + "=" * level + "]")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n" + BODY)
    print("wrote", out, len(parts), "parts,", len(rig["Rig"]), "motors")


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--") and "=" in a)
    main(args[0], args[1], args[2], opts.get("controller-out"))
