-- MeshSwap: swaps the part-built rocks (island + reef) AND the island's blocky cliffs for
-- the deformed, stud-textured Blender meshes.
--
-- 1. File > Import 3D > exports/meshes/VoxelRockMeshes.fbx         (all rocks, it lands in Workspace)
-- 2. File > Import 3D > exports/meshes/<IslandName>_Terrain.fbx    (for each island you inserted:
--    VoxelIsland_Terrain, DesertCoast_Terrain, FrostCoast_Terrain, VolcanicIsland_Terrain)
-- 3. Paste this whole file into the Command Bar (View > Command Bar) and press Enter.
--
-- The island's blocky ground stays underneath as invisible collision, so walking is unchanged.
--
-- Every mesh piece is placed from its exact size/centre (baked in below by Blender),
-- so it doesn't matter how the importer scaled or grouped the meshes.
-- Running it again is safe. Set UNDO = true and run it to put the part rocks back.

local UNDO = false

-- generated by tools/blender_meshes.py: asset -> mesh pieces (asset space, studs)
local PIECES = {
--@@PIECES@@
}
-- generated: island terrain mesh pieces (island space, studs)
local TERRAIN = {
--@@TERRAIN@@
}
local TERRAIN_BY_NAME = {}
for _, t in ipairs(TERRAIN) do
	TERRAIN_BY_NAME[t.name] = t
end
local PRECISE = { ReefShelf = true, ReefArch = true, ReefPinnacle = true, ReefPinnacleTall = true, Arch = true }
local MAPS = { "VoxelIsland", "CoralReef", "DesertCoast", "FrostCoast", "VolcanicIsland" }
local ISLANDS = { "VoxelIsland", "DesertCoast", "FrostCoast", "VolcanicIsland" }

local ServerStorage = game:GetService("ServerStorage")
local function waypoint(name)
	pcall(function()
		game:GetService("ChangeHistoryService"):SetWaypoint(name)
	end)
end

local backup = ServerStorage:FindFirstChild("VoxelPartRocks")
if not backup then
	backup = Instance.new("Folder")
	backup.Name = "VoxelPartRocks"
	backup.Parent = ServerStorage
end

-- remove meshes from an earlier run and put the part rocks back ---------------------
local function restore()
	local n = 0
	for _, mapName in ipairs(MAPS) do
		local map = workspace:FindFirstChild(mapName)
		if map then
			local old = {}
			for _, d in ipairs(map:GetDescendants()) do
				if d:IsA("Model") and d:GetAttribute("VoxelMesh") then
					table.insert(old, d)
				end
			end
			for _, d in ipairs(old) do
				d:Destroy()
			end
		end
	end
	for _, islandName in ipairs(ISLANDS) do
		local island = workspace:FindFirstChild(islandName)
		local ground = island and island:FindFirstChild("Ground")
		if ground then
			for _, p in ipairs(ground:GetDescendants()) do
				if p:IsA("BasePart") and p:GetAttribute("VoxelHidden") then
					p.Transparency = 0
					p.CastShadow = true
					p:SetAttribute("VoxelHidden", nil)
				end
			end
		end
	end
	for _, m in ipairs(backup:GetChildren()) do
		local home = m:FindFirstChild("VoxelOriginalParent")
		if home and home.Value and home.Value.Parent then
			m.Parent = home.Value
			home:Destroy()
			n += 1
		end
	end
	return n
end

waypoint("Before MeshSwap")
local restored = restore()
if UNDO then
	waypoint("MeshSwap undo")
	print(("[MeshSwap] restored %d part rocks"):format(restored))
	return
end

-- 1. find the imported mesh pieces (names like ReefShelf_Rock, maybe with .001 on the end)
local function norm(name)
	return (name:gsub("%.%d+$", ""))
end
local found = {}
for _, root in ipairs({ workspace, game:GetService("ReplicatedStorage"), ServerStorage }) do
	for _, top in ipairs(root:GetChildren()) do
		if top.Name ~= "VoxelIsland" and top.Name ~= "CoralReef" and top ~= backup then
			local list = top:GetDescendants()
			table.insert(list, top)
			for _, d in ipairs(list) do
				if d:IsA("MeshPart") then
					local key = norm(d.Name)
					if (PIECES[key:match("^(.-)_[^_]+$") or ""] or TERRAIN_BY_NAME[key]) and not found[key] then
						found[key] = d
					end
				end
			end
		end
	end
end

local ready, missing = {}, {}
local votes = { straight = 0, lying = 0 }
local function vote(size, want)
	local function spread(a, b)
		local r = { a.X / b.X, a.Y / b.Y, a.Z / b.Z }
		table.sort(r)
		return r[3] / r[1]
	end
	local straight = spread(size, want)
	local sideways = spread(size, Vector3.new(want.X, want.Z, want.Y))
	if straight < 1.1 and sideways > 1.2 then
		votes.straight += 1
	elseif sideways < 1.1 and straight > 1.2 then
		votes.lying += 1
	end
end
for name, pieces in pairs(PIECES) do
	local ok = true
	for _, piece in ipairs(pieces) do
		local tmpl = found[name .. piece.suffix]
		if not tmpl then
			ok = false
		else
			vote(tmpl.Size, piece.max - piece.min)
		end
	end
	if ok then
		ready[name] = pieces
	else
		table.insert(missing, name)
	end
end
local terrainFound, perMap, perMapFound = 0, {}, {}
for _, t in ipairs(TERRAIN) do
	perMap[t.map] = (perMap[t.map] or 0) + 1
	local tmpl = found[t.name]
	if tmpl then
		terrainFound += 1
		perMapFound[t.map] = (perMapFound[t.map] or 0) + 1
		vote(tmpl.Size, t.max - t.min)
	end
end
local LYING = votes.lying > votes.straight
if LYING then
	warn("[MeshSwap] the importer laid the meshes on their sides - standing them back up")
end
if next(ready) == nil and terrainFound == 0 then
	warn("[MeshSwap] No imported meshes found. Import exports/meshes/VoxelRockMeshes.fbx and the *_Terrain.fbx files first.")
	return
end
if #missing > 0 then
	table.sort(missing)
	warn("[MeshSwap] not found in the import (left as parts): " .. table.concat(missing, ", "))
end

-- 2. swap every tagged rock ----------------------------------------------------------
local swapped = 0
for _, mapName in ipairs(MAPS) do
	local map = workspace:FindFirstChild(mapName)
	if map then
		for _, m in ipairs(map:GetDescendants()) do
			local name = m:IsA("Model") and not m:GetAttribute("VoxelMesh") and m:GetAttribute("VoxelAsset")
			local pieces = name and ready[name]
			if pieces then
				local scale = m:GetAttribute("VoxelScale") or 1
				local ref, offset = m:FindFirstChild("VoxelRef"), m:GetAttribute("VoxelRefOffset")
				local cf = (ref and offset) and ref.CFrame * offset or m.WorldPivot
				local model = Instance.new("Model")
				model.Name = name
				for _, piece in ipairs(pieces) do
					local p = found[name .. piece.suffix]:Clone()
					p.Name = name .. piece.suffix
					local size = (piece.max - piece.min) * scale
					local at = cf * CFrame.new((piece.min + piece.max) * 0.5 * scale)
					if LYING then -- mesh's up is its local +Z
						p.Size = Vector3.new(size.X, size.Z, size.Y)
						p.CFrame = at * CFrame.Angles(math.rad(-90), 0, 0)
					else
						p.Size = size
						p.CFrame = at
					end
					p.Color = piece.color
					p.Anchored = true
					p.CanCollide = name ~= "Seaweed"
					p.CanTouch = false
					if PRECISE[name] then
						pcall(function()
							p.CollisionFidelity = Enum.CollisionFidelity.PreciseConvexDecomposition
						end)
					end
					p.Parent = model
				end
				model.WorldPivot = cf
				model:SetAttribute("VoxelPivot", cf)
				model:SetAttribute("VoxelAsset", name)
				model:SetAttribute("VoxelMesh", true)
				for _, d in ipairs(m:GetChildren()) do
					if d.Name == "LightSource" or d.Name == "FireSource" then
						d.Parent = model
					end
				end
				model.Parent = m.Parent
				local home = Instance.new("ObjectValue")
				home.Name = "VoxelOriginalParent"
				home.Value = m.Parent
				home.Parent = m
				m.Parent = backup
				swapped += 1
			end
		end
	end
end
-- 3. island terrain: deformed cliff meshes on top, blocky ground becomes invisible collision
for _, islandName in ipairs(ISLANDS) do
	local island = workspace:FindFirstChild(islandName)
	local anchor = island and island:FindFirstChild("VoxelAnchor")
	local have, need = perMapFound[islandName] or 0, perMap[islandName] or 0
	if island and anchor and have > 0 and have < need then
		warn(("[MeshSwap] %s terrain: only %d of %d pieces imported - import exports/meshes/%s_Terrain.fbx")
			:format(islandName, have, need, islandName))
	elseif island and anchor and have > 0 then
		local base = anchor.CFrame
		local model = Instance.new("Model")
		model.Name = "TerrainMesh"
		for _, t in ipairs(TERRAIN) do
			if t.map == islandName then
				local p = found[t.name]:Clone()
				p.Name = t.name
				local size = t.max - t.min
				local at = base * CFrame.new((t.min + t.max) * 0.5)
				if LYING then
					p.Size = Vector3.new(size.X, size.Z, size.Y)
					p.CFrame = at * CFrame.Angles(math.rad(-90), 0, 0)
				else
					p.Size = size
					p.CFrame = at
				end
				p.Color = t.color
				if t.material == "Neon" then
					p.Material = Enum.Material.Neon
				end
				p.Anchored = true
				p.CanCollide = false
				p.CanTouch = false
				p.CanQuery = false
				p.Parent = model
			end
		end
		model.WorldPivot = base
		model:SetAttribute("VoxelMesh", true)
		model.Parent = island
		local ground = island:FindFirstChild("Ground")
		if ground then
			for _, p in ipairs(ground:GetDescendants()) do
				if p:IsA("BasePart") then
					p.Transparency = 1
					p.CastShadow = false
					p:SetAttribute("VoxelHidden", true)
				end
			end
		end
		local cliffs = island:FindFirstChild("Cliffs")
		if cliffs then
			local home = Instance.new("ObjectValue")
			home.Name = "VoxelOriginalParent"
			home.Value = island
			home.Parent = cliffs
			cliffs.Parent = backup
		end
		print(("[MeshSwap] %s: placed %d deformed terrain meshes"):format(islandName, have))
	end
end

waypoint("MeshSwap")
print(("[MeshSwap] swapped %d rocks for meshes (part versions kept in ServerStorage.VoxelPartRocks)."):format(swapped))
print("[MeshSwap] You can delete the imported VoxelRockMeshes / *_Terrain models now.")
