-- Cube Monster: paste all of this into View -> Command Bar and press Enter.
-- Builds a blocky square-headed monster from anchored Parts in front of the camera.
-- Generated by tools/cube_monster.py.

local SCALE = 1          -- 1 = about 21 studs tall. 0.4 is player-sized.
local PARENT = workspace

local COLORS = {
	skin = {Color3.fromRGB(118, 200, 68), Enum.Material.SmoothPlastic},
	skin_dark = {Color3.fromRGB(80, 150, 46), Enum.Material.SmoothPlastic},
	spot = {Color3.fromRGB(96, 172, 54), Enum.Material.SmoothPlastic},
	belly = {Color3.fromRGB(196, 232, 132), Enum.Material.SmoothPlastic},
	brow = {Color3.fromRGB(48, 96, 32), Enum.Material.SmoothPlastic},
	horn = {Color3.fromRGB(242, 230, 198), Enum.Material.SmoothPlastic},
	horn_tip = {Color3.fromRGB(198, 182, 146), Enum.Material.SmoothPlastic},
	eye = {Color3.fromRGB(255, 212, 36), Enum.Material.SmoothPlastic},
	pupil = {Color3.fromRGB(22, 20, 26), Enum.Material.SmoothPlastic},
	shine = {Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic},
	mouth = {Color3.fromRGB(56, 14, 28), Enum.Material.SmoothPlastic},
	tongue = {Color3.fromRGB(228, 72, 98), Enum.Material.SmoothPlastic},
	tooth = {Color3.fromRGB(252, 250, 242), Enum.Material.SmoothPlastic},
}

-- {x0, y0, z0, x1, y1, z1, color} in studs, origin at the feet, facing -Z
local BOXES = {
	{0.700, 0.900, -1.300, 3.300, 3.300, 1.300, "skin"},
	{-3.300, 0.900, -1.300, -0.700, 3.300, 1.300, "skin"},
	{0.400, 0.000, -2.300, 3.600, 1.000, 1.366, "skin_dark"},
	{-3.600, 0.000, -2.300, -0.400, 1.000, 1.379, "skin_dark"},
	{0.800, 0.000, -2.800, 1.400, 0.600, -2.200, "horn"},
	{1.700, 0.000, -2.800, 2.300, 0.600, -2.200, "horn"},
	{2.600, 0.000, -2.800, 3.200, 0.600, -2.200, "horn"},
	{-3.200, 0.000, -2.800, -2.600, 0.600, -2.200, "horn"},
	{-2.300, 0.000, -2.800, -1.700, 0.600, -2.200, "horn"},
	{-1.400, 0.000, -2.800, -0.800, 0.600, -2.200, "horn"},
	{-3.500, 2.800, -2.500, 3.500, 8.400, 2.500, "skin"},
	{-2.200, 3.400, -2.650, 2.200, 7.200, -2.350, "belly"},
	{-1.200, 3.400, 2.200, 1.200, 5.200, 4.600, "skin"},
	{-0.800, 4.000, 4.400, 0.800, 5.279, 6.000, "skin_dark"},
	{-0.400, 5.200, 5.000, 0.400, 6.000, 5.800, "horn"},
	{3.400, 3.200, -1.400, 5.400, 8.200, 0.800, "skin"},
	{-5.400, 3.200, -1.400, -3.400, 8.200, 0.800, "skin"},
	{3.300, 2.000, -1.700, 5.700, 3.400, 0.900, "skin_dark"},
	{-5.700, 2.000, -1.700, -3.300, 3.400, 0.900, "skin_dark"},
	{4.250, 1.200, -1.850, 4.750, 2.100, -1.350, "horn"},
	{4.250, 1.200, -1.050, 4.750, 2.100, -0.550, "horn"},
	{4.250, 1.200, -0.250, 4.750, 2.100, 0.250, "horn"},
	{-4.750, 1.200, -1.850, -4.250, 2.100, -1.350, "horn"},
	{-4.750, 1.200, -1.050, -4.250, 2.100, -0.550, "horn"},
	{-4.750, 1.200, -0.250, -4.250, 2.100, 0.250, "horn"},
	{-5.000, 8.000, -4.500, 5.000, 17.000, 4.500, "skin"},
	{4.950, 13.000, 0.300, 5.150, 15.000, 2.700, "spot"},
	{4.950, 10.000, -1.700, 5.150, 11.400, -0.300, "spot"},
	{4.950, 14.600, -2.700, 5.150, 15.600, -1.700, "spot"},
	{-5.150, 13.000, 0.300, -4.950, 15.000, 2.700, "spot"},
	{-5.150, 10.000, -1.700, -4.950, 11.400, -0.300, "spot"},
	{-5.150, 14.600, -2.700, -4.950, 15.600, -1.700, "spot"},
	{-3.700, 17.000, 1.500, -1.500, 17.150, 3.300, "spot"},
	{2.100, 17.000, -0.300, 3.500, 17.150, 1.100, "spot"},
	{2.500, 16.908, -0.400, 4.300, 18.500, 1.400, "horn"},
	{3.200, 18.500, -0.200, 4.600, 19.800, 1.200, "horn"},
	{4.000, 19.800, 0.000, 5.000, 20.800, 1.000, "horn"},
	{4.600, 20.800, 0.200, 5.200, 21.500, 0.800, "horn_tip"},
	{-4.300, 17.000, -0.400, -2.500, 18.500, 1.400, "horn"},
	{-4.600, 18.500, -0.200, -3.200, 19.800, 1.200, "horn"},
	{-5.000, 19.800, 0.000, -4.000, 20.800, 1.000, "horn"},
	{-5.200, 20.800, 0.200, -4.600, 21.500, 0.800, "horn_tip"},
	{-0.500, 17.000, 1.500, 0.500, 18.100, 2.500, "skin_dark"},
	{-0.500, 17.000, 3.100, 0.500, 18.100, 4.100, "skin_dark"},
	{-0.250, 18.100, 1.750, 0.250, 18.600, 2.250, "skin_dark"},
	{1.000, 12.800, -4.750, 3.600, 15.400, -4.450, "eye"},
	{1.500, 13.300, -4.950, 2.700, 14.700, -4.650, "pupil"},
	{2.175, 14.100, -5.100, 2.625, 14.550, -4.900, "shine"},
	{2.200, 16.100, -5.000, 4.000, 16.800, -4.400, "brow"},
	{0.500, 15.300, -5.000, 2.300, 16.000, -4.400, "brow"},
	{-3.600, 12.800, -4.750, -1.000, 15.400, -4.450, "eye"},
	{-2.700, 13.300, -4.950, -1.500, 14.700, -4.650, "pupil"},
	{-2.025, 14.100, -5.100, -1.575, 14.550, -4.900, "shine"},
	{-4.000, 16.100, -5.000, -2.200, 16.800, -4.400, "brow"},
	{-2.300, 15.300, -5.000, -0.500, 16.000, -4.400, "brow"},
	{-3.800, 8.900, -4.750, 3.800, 12.100, -4.450, "mouth"},
	{-0.500, 8.940, -4.900, 2.100, 9.940, -4.600, "tongue"},
	{2.100, 10.500, -4.950, 3.100, 12.080, -4.550, "tooth"},
	{2.350, 10.000, -4.950, 2.850, 10.520, -4.550, "tooth"},
	{2.800, 8.920, -4.950, 3.700, 10.420, -4.550, "tooth"},
	{-3.100, 10.500, -4.950, -2.100, 12.080, -4.550, "tooth"},
	{-2.850, 10.000, -4.950, -2.350, 10.520, -4.550, "tooth"},
	{-3.700, 8.920, -4.950, -2.800, 10.420, -4.550, "tooth"},
	{-1.700, 11.200, -4.950, -0.900, 12.080, -4.550, "tooth"},
	{-0.400, 11.200, -4.950, 0.400, 12.080, -4.550, "tooth"},
	{0.900, 11.200, -4.950, 1.700, 12.080, -4.550, "tooth"},
	{-2.200, 8.920, -4.950, -1.400, 9.720, -4.550, "tooth"},
}

local cam = workspace.CurrentCamera
local look = cam.CFrame.LookVector
local flat = Vector3.new(look.X, 0, look.Z)
if flat.Magnitude < 0.01 then flat = Vector3.new(0, 0, -1) end
flat = flat.Unit
local spot = cam.CFrame.Position + flat * 40 * math.max(SCALE, 0.5)
local hit = workspace:Raycast(spot + Vector3.new(0, 200, 0), Vector3.new(0, -1000, 0))
local ground = hit and hit.Position or Vector3.new(spot.X, 0, spot.Z)
-- origin's -Z (LookVector) points back at the camera, so the monster's -Z face looks at you
local origin = CFrame.lookAt(ground, ground - flat)

local model = Instance.new("Model")
model.Name = "CubeMonster"
for i, b in ipairs(BOXES) do
	local p = Instance.new("Part")
	p.Name = b[7]
	p.Anchored = true
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	p.Size = Vector3.new(b[4] - b[1], b[5] - b[2], b[6] - b[3]) * SCALE
	local c = Vector3.new(b[1] + b[4], b[2] + b[5], b[3] + b[6]) / 2 * SCALE
	p.CFrame = origin * CFrame.new(c)
	p.Color = COLORS[b[7]][1]
	p.Material = COLORS[b[7]][2]
	p.Parent = model
end
model.WorldPivot = origin
model.Parent = PARENT
game:GetService("Selection"):Set({model})
print("CubeMonster built with " .. #BOXES .. " parts")
