"""Write the Roblox Studio Command Bar script that turns the imported FBX meshes
into the game's weapon Models.

    python tools/gen_rig.py <weapons.json> <out.lua>
"""
import json
import sys


def num(v):
    return ("%.4f" % v).rstrip("0").rstrip(".") if abs(v) > 1e-9 else "0"


def vec(v):
    return "{%s}" % ", ".join(num(x) for x in v)


HEADER = '''--[[
FOLK VALLEY [RUN] - weapon builder (generated by tools/gen_rig.py)

1. In Studio: File > Import 3D > choose FolkValley_Weapons.fbx > Import.
   Default import settings are fine ("Merge Meshes" must stay off).
2. View > Command Bar: paste ALL of this file and press Enter.

It builds a Folder "Weapons" in ServerStorage (named "Weapons (new)" if one is
already there) with one Model per weapon, named by its Id:
  * PrimaryPart "Handle": 0.4 x 0.4 x 0.4 Part, Transparency 1, at the grip
  * every visible part is a MeshPart named for what it is, welded to the Handle
    with a WeldConstraint; Anchored/CanCollide/CanTouch/CanQuery false, Massless true
  * number attributes "Top" and "Bottom" (studs above / below the Handle along Y)
  * an Attachment "Fx" under the Handle for Epic, Legendary, Limited and Mythic weapons
The imported model is cleaned up afterwards. Ctrl+Z undoes the whole thing.
3. Right-click the folder > Save to File... to get the .rbxm, or move it to
   wherever the game keeps its weapons.
]]

local HANDLE_AT = CFrame.new(0, 3000, 0)
local MARKER_STEP = %s
'''

BODY = r'''
local ChangeHistoryService = game:GetService("ChangeHistoryService")
local ServerStorage = game:GetService("ServerStorage")

-- 1. find the imported meshes (the importer puts them in Workspace)
local meshes = {}
for _, root in ipairs({workspace, ServerStorage, game:GetService("ReplicatedStorage")}) do
	for _, d in ipairs(root:GetDescendants()) do
		if d:IsA("MeshPart") and meshes[d.Name] == nil then
			meshes[d.Name] = d
		end
	end
end

local wanted = {"FV_AxisO", "FV_AxisX", "FV_AxisY", "FV_AxisZ"}
for _, w in ipairs(WEAPONS) do
	for _, p in ipairs(w.Parts) do
		table.insert(wanted, p.Mesh)
	end
end
local missing = {}
for _, name in ipairs(wanted) do
	if meshes[name] == nil then
		table.insert(missing, name)
	end
end
if #missing > 0 then
	warn("FolkValley weapons: " .. #missing .. " imported meshes not found (first: " .. missing[1]
		.. "). Import FolkValley_Weapons.fbx with File > Import 3D first, with Merge Meshes off.")
	return
end

-- 2. work out how the importer scaled / turned the file from the marker cubes
local o = meshes.FV_AxisO.Position
local ex = meshes.FV_AxisX.Position - o
local ey = meshes.FV_AxisY.Position - o
local ez = meshes.FV_AxisZ.Position - o
local scale = (ex.Magnitude + ey.Magnitude + ez.Magnitude) / (3 * MARKER_STEP)
if ex.Unit:Cross(ey.Unit):Dot(ez.Unit) < 0.9 then
	warn("FolkValley weapons: the import looks mirrored. Re-import with the default axis settings.")
	return
end
local fromFile = CFrame.fromMatrix(Vector3.zero, ex.Unit, ey.Unit, ez.Unit):Inverse()

ChangeHistoryService:SetWaypoint("Before building FolkValley weapons")

local folder = Instance.new("Folder")
folder.Name = ServerStorage:FindFirstChild("Weapons") and "Weapons (new)" or "Weapons"

local function setFlags(part)
	part.Anchored = false
	part.CanCollide = false
	part.CanTouch = false
	part.CanQuery = false
	part.Massless = true
end

local containers = {}
for _, w in ipairs(WEAPONS) do
	local model = Instance.new("Model")
	model.Name = w.Id

	local handle = Instance.new("Part")
	handle.Name = "Handle"
	handle.Size = Vector3.new(0.4, 0.4, 0.4)
	handle.Transparency = 1
	handle.TopSurface = Enum.SurfaceType.Smooth
	handle.BottomSurface = Enum.SurfaceType.Smooth
	handle.CFrame = HANDLE_AT
	setFlags(handle)
	handle.Parent = model

	for _, p in ipairs(w.Parts) do
		local part = meshes[p.Mesh]
		containers[part.Parent] = true
		local turn = fromFile * (part.CFrame - part.CFrame.Position)
		for _, child in ipairs(part:GetChildren()) do
			child:Destroy() -- importer extras (SurfaceAppearance, attachments)
		end
		part.Name = p.Name
		part.Size = part.Size / scale
		part.CFrame = HANDLE_AT * CFrame.new(p.Center[1], p.Center[2], p.Center[3]) * turn
		part.Color = Color3.fromRGB(p.Color[1], p.Color[2], p.Color[3])
		part.Material = Enum.Material[p.Material]
		part.Transparency = p.Transparency
		part.Reflectance = 0
		part.CastShadow = true
		pcall(function() part.TextureID = "" end)
		pcall(function() part.CollisionFidelity = Enum.CollisionFidelity.Box end)
		setFlags(part)
		part.Parent = model
		local weld = Instance.new("WeldConstraint")
		weld.Part0 = handle
		weld.Part1 = part
		weld.Parent = part
		local want = Vector3.new(p.Size[1], p.Size[2], p.Size[3])
		if (turn.LookVector - Vector3.new(0, 0, -1)).Magnitude < 1e-3 and (part.Size - want).Magnitude > 0.05 * want.Magnitude then
			warn(("FolkValley weapons: %s.%s came in at an unexpected size %s (expected %s)"):format(
				w.Id, p.Name, tostring(part.Size), tostring(want)))
		end
	end

	if w.Fx then
		local fx = Instance.new("Attachment")
		fx.Name = "Fx"
		fx.Position = Vector3.new(w.Fx[1], w.Fx[2], w.Fx[3])
		fx.Parent = handle
	end

	model.PrimaryPart = handle
	model.WorldPivot = HANDLE_AT
	model:SetAttribute("Top", w.Top)
	model:SetAttribute("Bottom", w.Bottom)
	model.Parent = folder
end

folder.Parent = ServerStorage

-- 3. tidy up: marker cubes and the now-empty imported model
for _, name in ipairs({"FV_AxisO", "FV_AxisX", "FV_AxisY", "FV_AxisZ"}) do
	containers[meshes[name].Parent] = true
	meshes[name]:Destroy()
end
for c in pairs(containers) do
	while c and c ~= game and c ~= workspace and c.Parent and not c:IsA("Folder") do
		local hasParts = false
		for _, d in ipairs(c:GetDescendants()) do
			if d:IsA("BasePart") then
				hasParts = true
				break
			end
		end
		if hasParts then
			break
		end
		local parent = c.Parent
		c:Destroy()
		c = parent
	end
end

ChangeHistoryService:SetWaypoint("Built FolkValley weapons")
game:GetService("Selection"):Set({folder})
print(("FolkValley weapons: built %d weapons in ServerStorage.%s"):format(#WEAPONS, folder.Name))
'''


def main(src, out):
    weapons = json.load(open(src))
    lines = [HEADER % 4, "local WEAPONS = {"]
    for w in weapons:
        fx = vec(w["Fx"]) if w.get("Fx") else "nil"
        lines.append('\t{Id = "%s", Rarity = "%s", Top = %s, Bottom = %s, Fx = %s, Parts = {' % (
            w["Id"], w["Rarity"], num(round(w["Top"], 2)), num(round(w["Bottom"], 2)), fx))
        for p in w["Parts"]:
            lines.append('\t\t{Name = "%s", Mesh = "%s", Color = %s, Material = "%s", Transparency = %s, '
                         'Center = %s, Size = %s},' % (p["Name"], p["Mesh"], vec(p["Color"]), p["Material"],
                                                       num(p["Transparency"]), vec(p["Center"]), vec(p["Size"])))
        lines.append("\t}},")
    lines.append("}")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n" + BODY)
    print("wrote", out, len(weapons), "weapons")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
